# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uQu0p0WPtwo_6J2W_4YcME1hMX7STjj
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("titanic.csv")

df.info()

df.head()

df.shape

print("Shape of Dataset:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

df['Age'].fillna(df['Age'].median(), inplace=True)

print(df.isnull().sum())

df.dtypes

df.isnull().sum()

df.describe()

plt.figure(figsize=(8,5))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.show()

sns.histplot(df['Age'].dropna(), kde=True, color='blue')
plt.title('Age Distribution')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

sns.countplot(x='Sex', data=df)
plt.title('Gender Distribution')
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Passenger Class vs Survival")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Fare'])
plt.title("Fare Outliers")
plt.show()

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title('Survival Rate by Ticket Class')
plt.show()

sns.boxplot(x=df['Fare'])
plt.title('Outlier Detection in Fare')
plt.show()

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(),
            annot=True,
            cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

print("Age Skewness :", df['Age'].skew())
print("Age Kurtosis :", df['Age'].kurt())

print(df[['Age','Fare']].corr(method='pearson'))

print(df[['Age','Fare']].corr(method='spearman'))

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Fare'] < lower) | (df['Fare'] > upper)]

print("Number of Outliers:", len(outliers))

from scipy import stats

z_scores = np.abs(stats.zscore(df['Fare']))

outliers = df[z_scores > 3]

print("Outliers using Z-Score:", len(outliers))

print("Average Survival Rate by Class")
print(df.groupby('Pclass')['Survived'].mean())

print("Average Survival Rate by Age")
print(df.groupby(pd.cut(df['Age'], bins=5))['Survived'].mean())

sns.pairplot(df, hue='Survived', diag_kind='kde')
plt.show()

df.to_csv("cleaned_dataset.csv", index=False)

from google.colab import files

files.download("titanic.csv")

